packageExtensions:
  '@videojs/babel-config@*':
    dependencies:
      "@babel/cli": "*"
      "@babel/runtime": "*"
  '@rollup/plugin-babel@*':
    dependencies:
      "@babel/core": "*"

yarnPath: .yarn/releases/yarn-4.0.0-rc.44.cjs
